[package]
name = "vfsstat"
version = "0.1.0"
authors = ["Mike Zeller <mike@mikezeller.net>"]
edition = "2018"

[dependencies]
kstat = "0.1"
zonename = "0.1"
clap = "2.32"

[[bin]]
path = "src/main.rs"
name = "vfsstat"

[profile.release]
lto = true
